int _putchar(char c);
void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int is_prime_number(int n);
int is_palindrome(char *s);
int wildcmp(char *s1, char *s2);
int natural_root(int x, int n);
int _base_number(int base, int n);
int compare_str(char *str, int i, int len);
char *_find_wildcard(char *str);
char *_compare_wildcard(char *str1, char *str2);
